project_id = "supabase-erp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://ram-setu-erp-ruddy.vercel.app"
additional_redirect_urls = ["http://localhost:3000/dashboard", "https://ram-setu-erp-ruddy.vercel.app/dashboard", "https://setu-erp-ruddy.vercel.app/dashboard"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
